### ISSUE TITLE
Fails on API request failed: cannot get a check monitor

### ISSUE THREAD

**Issue by heleeen** [mashiike/shimesaba#122]
I encountered an error while using shimesaba. The error message is as follows:

```
2024/02/02 02:34:24 [debug] call GetMonitor(******) # ****** is check monitor's id
2024/02/02 02:34:24 [error] service level objective[id=availability]: create report faileds: API request failed: Cannot get a check monitor
```

It appears that shimesaba is unable to retrieve the check monitor during the attempt to create a report.
I would like to hear your thoughts on how to treat this error.

Environment
- OS version: macOS Sonoma 14.2.1
- shimesaba version: v1.4.0

Command
```
$ shimesaba \
-config "./config.yml" \
-mackerel-apikey "******" \
--debug
```

**Comment by mashiike** [comment]
After investigating the issue, it appears that Mackerel check monitoring data cannot be obtained through GetMonitor. I plan to address this limitation in the upcoming updates. To avoid this error, I propose not collecting detailed information from the Monitor when dealing with Check monitoring.

I hadn't regularly used Check monitoring, so I was unaware that despite having the MonitorID, the details couldn't be retrieved using GetMonitor.

Thank you for bringing this issue to our attention.

**Comment by heleeen** [comment]
Appreciate the quick fix. Thank you! 😊

**Comment by mashiike** [comment]
Today, will release v1.4.1.
